name: ctseg
channels:
  - conda-forge
  - defaults
  - nvidia
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py311hc665b79_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=9.5.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.21.3=h723845a_4
  - ld_impl_linux-64=2.40=h12ee557_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgomp=15.1.0=h767d61c_5
  - libkrb5=1.21.3=h520c7b4_4
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hd590300_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.3=h26f9b46_0
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyhc872135_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.13=h1a3bd86_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=2_cp311
  - pyzmq=27.1.0=py311h2315fbb_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py311h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.2=py311h49ec1c0_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==0.23.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - anyio==4.11.0
      - appdirs==1.4.4
      - arrow==1.3.0
      - attrs==25.3.0
      - backoff==2.2.1
      - beautifulsoup4==4.13.5
      - blessed==1.22.0
      - boto3==1.40.50
      - botocore==1.40.50
      - cachetools==5.5.2
      - certifi==2025.8.3
      - charset-normalizer==2.1.1
      - click==8.2.1
      - contextlib2==21.6.0
      - contourpy==1.3.3
      - croniter==1.4.1
      - cycler==0.12.1
      - datasets==2.14.5
      - dateutils==0.6.12
      - deepdiff==7.0.1
      - dill==0.3.7
      - distlib==0.4.0
      - docker-pycreds==0.4.0
      - editor==1.6.6
      - einops==0.7.0
      - evaluate==0.4.1
      - fastapi==0.119.0
      - filelock==3.19.1
      - fonttools==4.60.0
      - frozenlist==1.7.0
      - fsspec==2023.6.0
      - gdown==4.7.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.51.3
      - h11==0.16.0
      - h5py==3.9.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.0
      - idna==3.10
      - imageio==2.33.0
      - importlib-resources==6.5.2
      - inquirer==3.4.1
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - kornia==0.7.2
      - kornia-rs==0.1.3
      - lazy-loader==0.4
      - lightning==2.0.9
      - lightning-cloud==0.5.70
      - lightning-utilities==0.15.2
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - monai==1.2.0
      - monailabel==0.8.5
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.7.0
      - multiprocess==0.70.15
      - networkx==3.5
      - nibabel==5.1.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauthlib==3.3.1
      - opencv-contrib-python==4.7.0.72
      - opencv-python==4.7.0.72
      - opencv-python-headless==4.7.0.72
      - opt-einsum==3.3.0
      - ordered-set==4.1.0
      - packaging==24.2
      - pandas==1.5.3
      - pathtools==0.1.2
      - pillow==11.3.0
      - platformdirs==3.11.0
      - propcache==0.4.1
      - protobuf==4.22.3
      - psutil==6.1.1
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==1.10.23
      - pyjwt==2.10.1
      - pyparsing==3.2.4
      - pysocks==1.7.1
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.5
      - pytz==2025.2
      - pyyaml==6.0.2
      - ray==2.4.0
      - readchar==4.2.1
      - referencing==0.36.2
      - requests==2.28.1
      - requests-oauthlib==2.0.0
      - responses==0.18.0
      - rich==14.2.0
      - rpds-py==0.27.1
      - rsa==4.9.1
      - runs==1.2.2
      - s3transfer==0.14.0
      - safetensors==0.3.1
      - scikit-image==0.23.1
      - scikit-learn==1.2.2
      - scipy==1.13.0
      - sentry-sdk==2.41.0
      - setproctitle==1.3.7
      - shapely==2.1.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - starlette==0.47.0
      - starsessions==1.3.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.3.0
      - threadpoolctl==3.6.0
      - tifffile==2025.9.9
      - timm==0.6.13
      - toml==0.10.2
      - torch==2.5.1
      - torch-geometric==2.3.0
      - torch-summary==1.4.5
      - torchmetrics==0.11.4
      - torchsummary==1.5.1
      - torchsummaryx==1.3.0
      - torchvision==0.20.1
      - tqdm==4.65.0
      - triton==3.1.0
      - types-python-dateutil==2.9.0.20251008
      - typing-extensions==4.8.0
      - tzdata==2025.2
      - unknown==0.0.0
      - urllib3==1.26.20
      - uvicorn==0.37.0
      - virtualenv==20.21.0
      - wandb==0.15.12
      - websocket-client==1.9.0
      - websockets==12.0
      - werkzeug==3.1.3
      - xmod==1.8.1
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /root/miniconda3/envs/ctseg
