name: ctseg
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py310hbdd6827_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyhc872135_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py310hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.18=h1a3bd86_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - pyzmq=27.1.0=py310hcf8288c_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py310h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - aiosignal==1.4.0
      - alembic==1.17.1
      - anyio==4.11.0
      - attrs==25.4.0
      - bcrypt==4.0.1
      - beautifulsoup4==4.14.2
      - blinker==1.9.0
      - cachetools==5.3.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpickle==3.1.1
      - contextlib2==21.6.0
      - contourpy==1.3.2
      - cryptography==46.0.3
      - cycler==0.12.1
      - databricks-sdk==0.71.0
      - dicomweb-client==0.59.1
      - diskcache==5.6.3
      - distlib==0.4.0
      - docker==7.1.0
      - ecdsa==0.19.1
      - einops==0.8.1
      - expiring-dict==1.1.0
      - expiringdict==1.2.2
      - fastapi==0.95.0
      - filelock==3.11.0
      - fire==0.7.1
      - flask==3.1.2
      - flask-cors==6.0.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gdown==4.7.1
      - girder-client==3.1.17
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.42.1
      - google-auth-oauthlib==1.0.0
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.2.4
      - grpcio==1.51.3
      - gunicorn==23.0.0
      - h11==0.14.0
      - hf-xet==1.2.0
      - httpcore==0.16.3
      - httpx==0.23.3
      - huggingface-hub==1.0.1
      - idna==3.11
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - itk==5.4.4.post1
      - itk-core==5.4.4.post1
      - itk-filtering==5.4.4.post1
      - itk-io==5.4.4.post1
      - itk-numerics==5.4.4.post1
      - itk-registration==5.4.4.post1
      - itk-segmentation==5.4.4.post1
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==3.2.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lmdb==1.7.5
      - mako==1.3.10
      - markdown==3.9
      - markupsafe==2.1.5
      - matplotlib==3.7.1
      - ml-collections==0.1.1
      - mlflow==3.5.1
      - mlflow-skinny==3.5.1
      - mlflow-tracing==3.5.1
      - monai==1.2.0
      - monailabel==0.7.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - networkx==3.3
      - nibabel==5.3.2
      - ninja==1.11.1
      - nptyping==2.5.0
      - numpy==1.26.4
      - numpymaxflow==0.0.5
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.6.77
      - oauthlib==3.3.1
      - opencv-python-headless==4.7.0.72
      - openslide-python==1.1.2
      - opentelemetry-api==1.38.0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - pandas==1.5.3
      - passlib==1.7.4
      - pillow==11.3.0
      - platformdirs==3.11.0
      - protobuf==4.22.3
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==1.10.24
      - pydicom==2.3.1
      - pydicom-seg==0.4.1
      - pynetdicom==2.0.2
      - pynrrd==1.0.0
      - pyparsing==3.2.5
      - pyrsistent==0.20.0
      - pysocks==1.7.1
      - python-dotenv==1.0.0
      - python-jose==3.3.0
      - python-multipart==0.0.6
      - pytorch-ignite==0.4.11
      - pytz==2025.2
      - pyyaml==6.0
      - ray==2.4.0
      - referencing==0.37.0
      - requests==2.28.2
      - requests-oauthlib==2.0.0
      - requests-toolbelt==0.10.1
      - retrying==1.4.2
      - rfc3986==1.5.0
      - rpds-py==0.28.0
      - rsa==4.9.1
      - schedule==1.1.0
      - scikit-image==0.25.2
      - scikit-learn==1.2.2
      - scipy==1.15.3
      - shapely==2.0.1
      - shellingham==1.5.4
      - simpleitk==2.5.2
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - sqlparse==0.5.3
      - starlette==0.26.1
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timeloop==1.0.2
      - timm==0.6.13
      - toml==0.10.2
      - tomli==2.3.0
      - torch==2.9.0+cu126
      - torchsummaryx==1.3.0
      - torchvision==0.24.0+cu126
      - tqdm==4.67.1
      - triton==3.5.0
      - typer-slim==0.20.0
      - tzdata==2025.2
      - urllib3==1.26.20
      - uvicorn==0.21.1
      - virtualenv==20.21.0
      - watchdog==3.0.0
      - werkzeug==3.1.3
prefix: /root/anaconda3/envs/ctseg
